<?php

// banner
$lang['apr_recent_draft'] = 'The <a href="%s">most recent version</a> of this page is a draft.';
$lang['apr_outdated'] = 'This version is <em>outdated</em> by a <a href="%s">newer approved version</a>.';
$lang['apr_draft'] = 'This version (%s) is a <em>draft</em>.';
$lang['apr_approved'] = 'This version (%s) was <em>approved</em> by %s.';
$lang['apr_previous'] = 'The <a href="%s">Previously approved version</a> (%s) is available.';

// Pending Approvals List
$lang['apr_p_none'] = 'No documents pending approval';
$lang['apr_p_hdr_page'] = 'Page';
$lang['apr_p_hdr_previous'] = 'Previous Approval';
$lang['apr_p_hdr_updated'] = 'Updated';
$lang['apr_p_approved'] = 'By %s on <a href="%s">%s</a>';

// Submit (Next to the tick-box to approve a page)
$lang['apr_do_approve'] = 'Approve';


$lang['wrong permissions to approve'] = 'You have not the right permissions to approve this page.';
$lang['cannot approve a non-existing revision'] = 'You cannot approve a non-existing revision.';
$lang['version approved'] = 'You have approved the document.';
$lang['cannot approve error'] = 'Cannot approve due some technical errors (permissions?)';

$lang['approvals'] = 'Approvals: %s/%s';
$lang['approved by'] = 'Approved by: %s';
$lang['approve action'] = 'Approve document';


$lang['apr_changemail_text'] = 'Hi @FULLNAME@!

A new suggestion for @TITLE@ at @DOKUWIKIURL@

Changes: @CHANGES@

Approve Reject: @APPREJ@

--
This mail was generated by DokuWiki at
@DOKUWIKIURL@';

$lang['apr_approvemail_text'] = 'Hi @FULLNAME@!

Your suggestion for @TITLE@ at @DOKUWIKIURL@

URL: @URL@

is approved.

--
This mail was generated by DokuWiki at
@DOKUWIKIURL@';

$lang['apr_rejectmail_text'] = 'Hi @FULLNAME@!

Your suggestion for @TITLE@ at @DOKUWIKIURL@

URL: @URL@

is reject.

--
This mail was generated by DokuWiki at
@DOKUWIKIURL@';

$lang['apr_do_reject'] = 'Reject';
$lang['apr_do_approve'] = 'Approve';
$lang['apr_mail_subject'] = 'new suggestion';
$lang['apr_mail_app_subject'] = 'suggestion approved';
$lang['apr_mail_rej_subject'] = 'suggestion rejected';
